name: esc_pos_bluetooth
description: The library allows to print receipts using an ESC/POS thermal Bluetooth printer.
version: 0.4.1
homepage: https://github.com/andrey-ushakov/esc_pos_bluetooth

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  esc_pos_utils: 
    git:
      url: https://github.com/shajin-screl/flutter_esc_pos_utils_isselo
  flutter_bluetooth_basic:
    git:
      url: https://github.com/screlinfo/flutter_bluetooth_basic_isselo

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
